##############################################
# Example configuration file for dcos-metrics.
##############################################

# Collector configuration
collector:
  http_profiler: false
  node:
    polling_period: 15 

  mesos_agent:
    polling_period: 15
    port: 5051


# Producers configuration
producers:
  # HTTP producer
  http:
    port: 9000
